name: Issue
on:
  issues:
    types: [opened, edited, milestoned]
jobs:
  output-info:
    runs-on: ubuntu-latest
    steps:
      - name: outpur event details
        run: echo "${{toJSON(github.event)}}"
